# **19CSE305: MACHINE LEARNING LAB 2**

PYTHON BASICS : EXCERCISES

ROLL NUMBER: 

In [ ]:
PYTHON BASIC EXCERSISE

1)Get two positive integers start and end from the user and write a Python program to print all Prime numbers in that Interval.
2) Given a list of strings( Entered by the user), write program to get a percentage share of each word in the strings list.
percentage := (Occurrence of a word / Total words) * 100
3)Check if  given number is Fibonacci number or not. Given an integer ‘n’( Entered by the user), write a Python function that returns true if n  is Fibonacci number else return false.
4)Write a program to check if all digits of a number divide it. Given a number n( Entered by the user), find whether all digits of n divide it or not.
5)Get a given array as input from the user and split it from a specified position, and move the first part of array add to the end.
example:
Input : {1, 2, 3, 4, 5}, k = 3
Output :{4,5,1,2,3}


NUMPY BASIC EXCERSISE

1) Create a 2D array of shape 4x5 that contains random decimal numbers between 3 and 10.
2) Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3) Given a NumPy array of temperature values, convert the values of Fahrenheit degrees into Centigrade degrees. 
4) Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5) Write a NumPy program to extract third and fourth elements of the second and third rows from a given (3x4) array.



  #PYTHON BASIC EXCERCISE

#Question-1

In [ ]:
start=int(input("Enter the start range:"))
end=int(input("Enter the end range:"))
print("Prime Numbers between",start,"and",end,"are :")
for num in range(start,end+1):
  if num>1:
    for i in range(2,num):
      if (num%i==0):
        break
    else:
        print(num)

Enter the start range:2
Enter the end range:10
Prime Numbers between 2 and 10 are :
2
3
5
7


#Question-2

In [7]:
def word_percentage(strr):
  count={}
  words=strr.split()
  ash=0
  for word in words:
    if word in count.keys():
      count[word]+=1
    else:
      count[word]=1
    ash+=1
 
  #print(count)
  for i in count.keys():
    print(i,count[i]/ash*100)

word_percentage("the quick brown fox jumps over the lazy dog")

the 22.22222222222222
quick 11.11111111111111
brown 11.11111111111111
fox 11.11111111111111
jumps 11.11111111111111
over 11.11111111111111
lazy 11.11111111111111
dog 11.11111111111111


#Question-4



In [10]:

def check_divisibility(n,digit):
  return (digit!=0 and n%digit==0)

def allDigitsDiv(n):
  temp=n
  while(temp>0):
    digit=temp%10
    if((check_divisibility(n,digit))==False):
      return False

    temp=temp//10
  return True

n=int(input())
if(allDigitsDiv(n)):
  print("Yes")
else:
  print("No")



130
No


#Question-5




In [21]:

def splitArr(arr, n, k):
	for i in range(0, k):
		x = arr[0]
		for j in range(0, n-1):
			arr[j] = arr[j + 1]
		
		arr[n-1] = x
		


arr = [12, 10, 5, 6, 52, 36]
n = len(arr)
position = 3

splitArr(arr, n, position)

for i in range(0, n):
	print(arr[i], end = ' ')

6 52 36 12 10 5 

#NumPy

#Question-1

In [14]:
import numpy as np
x = np.random.random((4,5))
print("Original Array:")
print(x) 

Original Array:
[[0.41437129 0.322962   0.89876993 0.79687481 0.8278126 ]
 [0.70161847 0.75012358 0.82053695 0.33664101 0.5900614 ]
 [0.86134492 0.56408507 0.56829305 0.60679591 0.79827136]
 [0.72217041 0.59063459 0.4476443  0.34754701 0.7042493 ]]


#Question-2

In [18]:
from numpy import random
arr = random.randint(8,size=(1,6))
print("Original Array : \n",arr)
newarr =  arr.reshape(2,3)
print("\nConvert it to a 2D array with 2 rows : \n",newarr)

Original Array : 
 [[7 5 6 2 2 5]]

Convert it to a 2D array with 2 rows : 
 [[7 5 6]
 [2 2 5]]


#Question-3

In [23]:
import numpy as np
fvalues = [0, 12, 45.21, 34, 99.91, 32]
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:")
print(np.round((5*F/9 - 5*32/9),2))

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91 32.  ]
Values in  Centigrade degrees:
[-17.78 -11.11   7.34   1.11  37.73   0.  ]
