Roll No: CB.EN.U4CSE20271

In [ ]:
import pandas as pd
import numpy as np
import scipy as sci

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/nba.csv")

In [ ]:
df.sample(10)

Name                  Team  Number Position   Age Height  \
342         Gerald Green            Miami Heat    14.0       SF  30.0    6-7   
115        Julius Randle    Los Angeles Lakers    30.0       PF  21.0    6-9   
144           Seth Curry      Sacramento Kings    30.0       SG  25.0    6-2   
166  Matthew Dellavedova   Cleveland Cavaliers     8.0       PG  25.0    6-4   
292     Kendrick Perkins  New Orleans Pelicans     5.0        C  31.0   6-10   
453         Shelvin Mack             Utah Jazz     8.0       PG  26.0    6-3   
139         Caron Butler      Sacramento Kings    31.0       SF  36.0    6-7   
163         Bobby Portis         Chicago Bulls     5.0       PF  21.0   6-11   
116     D'Angelo Russell    Los Angeles Lakers     1.0       PG  20.0    6-5   
100           Chris Paul  Los Angeles Clippers     3.0       PG  31.0    6-0   

     Weight       College      Salary  
342   205.0           NaN    947276.0  
115   250.0      Kentucky   3132240.0  
144   185.0          Duke    947276.0  
166   198.0  Saint Mary's   1147276.0  
292   270.0           NaN    947276.0  
453   203.0        Butler   2433333.0  
139   228.0   Connecticut   1449187.0  
163   230.0      Arkansas   1391160.0  
116   195.0    Ohio State   5103120.0  
100   175.0   Wake Forest  21468695.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      457 non-null    object 
 1   Team      457 non-null    object 
 2   Number    457 non-null    float64
 3   Position  457 non-null    object 
 4   Age       457 non-null    float64
 5   Height    457 non-null    object 
 6   Weight    457 non-null    float64
 7   College   373 non-null    object 
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB


In [ ]:
df.describe()

Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [ ]:
df.describe(include=['object'])

Name                  Team Position Height   College
count             457                   457      457    457       373
unique            457                    30        5     18       118
top     Avery Bradley  New Orleans Pelicans       SG    6-9  Kentucky
freq                1                    19      102     59        22

In [ ]:
df.isna().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [ ]:
df1 = df.copy()
df1 = df1.dropna(axis=0)
df1.isna().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [ ]:
df1.shape

(364, 9)

In [ ]:
df2 = df.copy()
df2['Salary']=df2['Salary'].fillna(df2['Salary'].mean())
df2.dropna(axis=0,inplace=True, how='any')
df2.isna().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
dtype: int64

In [ ]:
df2.shape

(373, 9)

In [ ]:
from sklearn.impute import SimpleImputer
df3 = df.copy()
df3['Salary_Missing'] = df3['Salary'].isnull()
df3.dropna(axis=0,inplace=True, how='any', subset=['Name', 'Team', 'Position', 'Height', 'College'])

my_imputer = SimpleImputer(missing_values=np.NaN, strategy = 'mean') 
new_data = my_imputer.fit_transform(df3['Salary'].values.reshape(-1,1))[:,0]
df3.Salary = new_data

df3.isnull().sum()

Name              0
Team              0
Number            0
Position          0
Age               0
Height            0
Weight            0
College           0
Salary            0
Salary_Missing    0
dtype: int64

In [ ]:
df3.sample(10)

Name                   Team  Number Position   Age  \
213  Michael Carter-Williams        Milwaukee Bucks     5.0       PG  24.0   
96             Blake Griffin   Los Angeles Clippers    32.0       PF  27.0   
95                Jeff Green   Los Angeles Clippers     8.0       SF  29.0   
145               Duje Dukan       Sacramento Kings    26.0       PF  24.0   
383           Darrell Arthur         Denver Nuggets     0.0       PF  28.0   
266           JaMychal Green      Memphis Grizzlies     0.0       PF  25.0   
159           Doug McDermott          Chicago Bulls     3.0       SF  24.0   
239            Dwight Powell       Dallas Mavericks     7.0       PF  24.0   
87              Brandon Rush  Golden State Warriors     4.0       SF  30.0   
185           Reggie Bullock        Detroit Pistons    25.0       SF  25.0   

    Height  Weight         College      Salary  Salary_Missing  
213    6-6   190.0        Syracuse   2399040.0           False  
96    6-10   251.0        Oklahoma  18907726.0           False  
95     6-9   235.0      Georgetown   9650000.0           False  
145    6-9   220.0       Wisconsin    525093.0           False  
383    6-9   235.0          Kansas   2814000.0           False  
266    6-9   227.0         Alabama    845059.0           False  
159    6-8   225.0       Creighton   2380440.0           False  
239   6-11   240.0        Stanford    845059.0           False  
87     6-6   220.0          Kansas   1270964.0           False  
185    6-7   205.0  North Carolina   1252440.0           False

In [ ]:
df3['Height_In_Inches'] = df3['Height'].apply(lambda x: 12*int(x[:1]) + int(x[2:]))
df3.drop('Height', inplace=True, axis=1)

In [ ]:
df3.sample(5)

Name                    Team  Number Position   Age  Weight  \
8       Terry Rozier          Boston Celtics    12.0       PG  22.0   190.0   
429  Pat Connaughton  Portland Trail Blazers     5.0       SG  23.0   206.0   
372      Drew Gooden      Washington Wizards    90.0       PF  34.0   250.0   
51    Richaun Holmes      Philadelphia 76ers    22.0       PF  22.0   245.0   
145       Duje Dukan        Sacramento Kings    26.0       PF  24.0   220.0   

           College     Salary  Salary_Missing  Height_In_Inches  
8       Louisville  1824360.0           False                74  
429     Notre Dame   625093.0           False                77  
372         Kansas  3300000.0           False                82  
51   Bowling Green  1074169.0           False                82  
145      Wisconsin   525093.0           False                81

In [ ]:
df4 = df3.copy()
df4.duplicated().sum()

0

In [ ]:

df4 = pd.concat([df4]*2, ignore_index=True)


In [ ]:
df4.duplicated().sum()

373

In [ ]:
df4[df4.duplicated()]

Name            Team  Number Position   Age  Weight  \
373  Avery Bradley  Boston Celtics     0.0       PG  25.0   180.0   
374    Jae Crowder  Boston Celtics    99.0       SF  25.0   235.0   
375   John Holland  Boston Celtics    30.0       SG  27.0   205.0   
376    R.J. Hunter  Boston Celtics    28.0       SG  22.0   185.0   
377  Jordan Mickey  Boston Celtics    55.0       PF  21.0   235.0   
..             ...             ...     ...      ...   ...     ...   
741    Rodney Hood       Utah Jazz     5.0       SG  23.0   206.0   
742  Chris Johnson       Utah Jazz    23.0       SF  26.0   206.0   
743     Trey Lyles       Utah Jazz    41.0       PF  20.0   234.0   
744   Shelvin Mack       Utah Jazz     8.0       PG  26.0   203.0   
745    Jeff Withey       Utah Jazz    24.0        C  26.0   231.0   

               College        Salary  Salary_Missing  Height_In_Inches  
373              Texas  7.730337e+06           False                74  
374          Marquette  6.796117e+06           False                78  
375  Boston University  4.620311e+06            True                77  
376      Georgia State  1.148640e+06           False                77  
377                LSU  1.170960e+06           False                80  
..                 ...           ...             ...               ...  
741               Duke  1.348440e+06           False                80  
742             Dayton  9.813480e+05           False                78  
743           Kentucky  2.239800e+06           False                82  
744             Butler  2.433333e+06           False                75  
745             Kansas  9.472760e+05           False                84  

[373 rows x 10 columns]

In [ ]:
df4.drop_duplicates(keep = 'first', inplace = True) 

In [ ]:
df4.duplicated().sum()

373

In [ ]:


from sklearn import preprocessing
  
label_encoder = preprocessing.LabelEncoder()
  
df4['Name']= label_encoder.fit_transform(df4['Name'])
df4['College']= label_encoder.fit_transform(df4['College'])

df4.sample(10)

Name  Number  Position   Age  Weight  College      Salary  \
71     38     4.0       3.0  30.0   220.0       43   1270964.0   
172   117    40.0       4.0  22.0   222.0       57   1100000.0   
254    15    24.0       2.0  40.0   200.0       99    250750.0   
222   136     0.0       1.0  25.0   227.0        0    845059.0   
261     4    15.0       0.0  30.0   245.0       28  12000000.0   
196    79    42.0       1.0  33.0   245.0       28   2085671.0   
345   222     5.0       3.0  28.0   228.0       26   4500000.0   
232   235     8.0       3.0  26.0   225.0       63   1100602.0   
358    44     3.0       4.0  24.0   200.0       47   2525160.0   
158   342    34.0       3.0  23.0   235.0       91  16000000.0   

     Salary_Missing  Height_In_Inches    0  ...   20   21   22   23   24   25  \
71            False                78  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
172           False                79  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
254           False                75  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
222           False                81  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
261           False                82  1.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
196           False                81  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
345           False                80  0.0  ...  1.0  0.0  0.0  0.0  0.0  0.0   
232           False                81  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   
358           False                76  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0   
158           False                81  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0   

      26   27   28   29  
71   0.0  0.0  0.0  0.0  
172  0.0  0.0  0.0  0.0  
254  1.0  0.0  0.0  0.0  
222  0.0  0.0  0.0  0.0  
261  0.0  0.0  0.0  0.0  
196  0.0  0.0  0.0  0.0  
345  0.0  0.0  0.0  0.0  
232  0.0  0.0  0.0  0.0  
358  0.0  0.0  0.0  0.0  
158  0.0  0.0  0.0  0.0  

[10 rows x 39 columns]

In [ ]:


from sklearn.preprocessing import OrdinalEncoder
ord1 = OrdinalEncoder()

ord1.fit([df4['Position']])

df4['Position'] = ord1.fit_transform(df4[['Position']])
df4.sample(10)

Name                  Team  Number  Position   Age  Weight  \
136     Derrick Rose         Chicago Bulls     1.0       2.0  27.0   190.0   
531    Tobias Harris       Detroit Pistons    34.0       3.0  23.0   235.0   
456       Chris Paul  Los Angeles Clippers     3.0       2.0  31.0   175.0   
231    Ryan Anderson  New Orleans Pelicans    33.0       1.0  28.0   240.0   
472       Nick Young    Los Angeles Lakers     0.0       3.0  31.0   210.0   
650     Courtney Lee     Charlotte Hornets     1.0       4.0  30.0   200.0   
684  Otto Porter Jr.    Washington Wizards    22.0       3.0  23.0   198.0   
392      Brook Lopez         Brooklyn Nets    11.0       0.0  28.0   275.0   
390  Sean Kilpatrick         Brooklyn Nets     6.0       4.0  26.0   219.0   
248    Kyle Anderson     San Antonio Spurs     1.0       3.0  22.0   230.0   

              College      Salary  Salary_Missing  Height_In_Inches  
136           Memphis  20093064.0           False                75  
531         Tennessee  16000000.0           False                81  
456       Wake Forest  21468695.0           False                72  
231        California   8500000.0           False                82  
472               USC   5219169.0           False                79  
650  Western Kentucky   5675000.0           False                77  
684        Georgetown   4662960.0           False                80  
392          Stanford  19689000.0           False                84  
390        Cincinnati    134215.0           False                76  
248              UCLA   1142880.0           False                81

In [ ]:

from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc = enc.fit_transform(df4[['Team']]).toarray()
encoded_colm = pd.DataFrame(enc)

df4 = pd.concat([df4, encoded_colm], axis = 1)

df4 = df4.drop(['Team'], axis = 1)
df4.head(10)

KeyError: ignored

In [ ]:
df4.drop(['Salary_Missing'], axis=1, inplace=True)

In [ ]:
df5 = df4.pop('Salary') 
df4['Salary']=df5
df4.sample(10)

Name  Number  Position   Age  Weight  College  Height_In_Inches    0  \
338   191    34.0       3.0  24.0   230.0       88                79  0.0   
229    10    35.0       1.0  28.0   270.0       98                82  0.0   
84    284    34.0       3.0  38.0   235.0       43                79  0.0   
246   287    20.0       3.0  28.0   220.0      107                79  0.0   
123    30    23.0       4.0  23.0   195.0       43                77  0.0   
368   303     5.0       4.0  23.0   206.0       26                80  0.0   
67     97    23.0       1.0  26.0   230.0       58                79  0.0   
238   144     4.0       3.0  25.0   210.0       48                79  0.0   
206    67    33.0       4.0  30.0   186.0       28                81  0.0   
53     82    10.0       4.0  26.0   220.0       98                79  0.0   

       1    2  ...   21   22   23   24   25   26   27   28   29        Salary  
338  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.140240e+06  
229  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  4.620311e+06  
84   0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.376000e+06  
246  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  3.382023e+06  
123  0.0  0.0  ...  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  3.156600e+06  
368  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.348440e+06  
67   0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.426087e+07  
238  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  8.450590e+05  
206  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  8.229375e+06  
53   0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.005000e+07  

[10 rows x 38 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
array = df4.values
x=array[:,0:37]
y=array[:,37]
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(x)
np.set_printoptions(precision=3)
rescaledX[0:5,:]


array([[0.078, 0.   , 0.5  , 0.286, 0.161, 0.795, 0.294, 0.   , 1.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.374, 1.   , 0.75 , 0.286, 0.627, 0.444, 0.529, 0.   , 1.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.476, 0.303, 1.   , 0.381, 0.373, 0.068, 0.471, 0.   , 1.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.774, 0.283, 1.   , 0.143, 0.203, 0.282, 0.471, 0.   , 1.   ,
        0.   , 0.   , 0.   , 

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler().fit(x)
rescaledX=scaler.transform(x)
rescaledX[0:5,:]

array([[-1.458, -1.13 , -0.132, -0.388, -1.579,  1.09 , -1.462, -0.174,
         5.262, -0.19 , -0.19 , -0.182, -0.182, -0.182, -0.157, -0.205,
        -0.182, -0.174, -0.182, -0.197, -0.182, -0.219, -0.174, -0.197,
        -0.157, -0.212, -0.174, -0.197, -0.166, -0.205, -0.19 , -0.205,
        -0.19 , -0.174, -0.166, -0.166, -0.19 ],
       [-0.436,  5.49 ,  0.601, -0.388,  0.612, -0.171, -0.253, -0.174,
         5.262, -0.19 , -0.19 , -0.182, -0.182, -0.182, -0.157, -0.205,
        -0.182, -0.174, -0.182, -0.197, -0.182, -0.219, -0.174, -0.197,
        -0.157, -0.212, -0.174, -0.197, -0.166, -0.205, -0.19 , -0.205,
        -0.19 , -0.174, -0.166, -0.166, -0.19 ],
       [-0.084,  0.876,  1.334,  0.083, -0.583, -1.525, -0.555, -0.174,
         5.262, -0.19 , -0.19 , -0.182, -0.182, -0.182, -0.157, -0.205,
        -0.182, -0.174, -0.182, -0.197, -0.182, -0.219, -0.174, -0.197,
        -0.157, -0.212, -0.174, -0.197, -0.166, -0.205, -0.19 , -0.205,
        -0.19 , -0.174, -0.166, -0.166

In [ ]:
from sklearn.preprocessing import Normalizer
scaler=Normalizer().fit(x)
normalizedX=scaler.transform(x)
normalizedX[0:5,:]

array([[0.132, 0.   , 0.009, 0.114, 0.822, 0.425, 0.338, 0.   , 0.005,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.454, 0.323, 0.01 , 0.082, 0.767, 0.17 , 0.255, 0.   , 0.003,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.622, 0.105, 0.014, 0.095, 0.72 , 0.028, 0.271, 0.   , 0.004,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   ],
       [0.813, 0.079, 0.011, 0.062, 0.522, 0.093, 0.217, 0.   , 0.003,
        0.   , 0.   , 0.   , 

In [ ]:

from sklearn.preprocessing import Binarizer
binarizer=Binarizer(threshold=0.0).fit(x)
binaryX=binarizer.transform(x)
binaryX[0:5,:]


array([[1., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0.]])

In [ ]:

from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.30)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(261, 37) (112, 37) (261,) (112,)


In [ ]:
X_train

array([[121.,   4.,   1., ...,   0.,   0.,   0.],
       [301.,  50.,   0., ...,   0.,   0.,   0.],
       [ 79.,  42.,   1., ...,   0.,   0.,   0.],
       ...,
       [ 69.,   1.,   4., ...,   0.,   0.,   0.],
       [338.,  41.,   1., ...,   0.,   0.,   0.],
       [  4.,  15.,   0., ...,   0.,   0.,   0.]])